services:
  mysql:
    image: mysql:8.4
    container_name: payflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: PayFlow
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+09:00
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
